[package]
name = "project"
version = "0.1.0"
edition = "2024"

[dependencies]
# Local dependencies
transport = { path = "../transport" }
primitives = { path = "../primitives" }
marker-region = { path = "../marker-region" }
tracks = { path = "../tracks" }

# External dependencies
anyhow = "1.0.100"
async-trait = "0.1.89"
base64 = "0.22.1"
futures-util = "0.3.31"
helgoboss-midi = "0.4.0"
matchit = "0.9.0"
rosc = "0.11.4"
serde = {version = "1.0.228", features = ["derive"]}
serde_derive = "1.0.228"
serde_json = "1.0.145"
uuid = { version = "1.18.1", features = ["v4"] }

# Server dependencies (excluded for WASM builds)
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
axum = {version = "0.8.6", features = ["default"]}
http = "1.3.1"
hyper = "1.8.0"
tokio = { version = "1.48.0", features = ["full"] }
tonic = "0.14.2"
tower = { version = "0.5.2", features = ["full"] }
tower-layer = "0.3.3"
tower-service = "0.3.3"
