[package]
name = "keyflow"
version.workspace = true
edition.workspace = true

[dependencies]
tracing = "0.1"
color-eyre = "0.6"
serde = { version = "1.0", features = ["derive"] }
colored = "2.0"
regex = "1.11.3"

[dev-dependencies]
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }

[[example]]
name = "reckless_love"
path = "examples/simple/reckless_love.rs"

[[example]]
name = "build_my_life"
path = "examples/simple/build_my_life.rs"
